rails-112911/railsbook/config/routes.rb
Railsbook::Application.routes.draw do

  # Registration & sessions

  # FIXME change /register to /signup
  get   "register" => "users#new",             :as => :register
  post  "register" => "users#create"

  get   "login"    => "user_sessions#new",     :as => :login
  match "logout"   => "user_sessions#destroy", :as => :logout

  post "friend" => "users#friend", :as => :friend
  post "unfriend" => "users#unfriend", :as => :unfriend

  # FIXME Add routes for comments

  get   '/' => 'home#index', :as => :home

  resources :users
  resources :posts
  resources :user_sessions

  root :to => 'home#index'

end

rails-112911/railsbook/app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => 'User'

  after_create  :create_inverse
  after_destroy :destroy_inverse

  # For every user, friends must be unique
  validates_uniqueness_of :friend_id, :scope => :user_id

  # @return [Friendship] where +user_id+ and +friend_id+ are swapped
  #
  def inverse
    @inverse ||= Friendship.find_by_friend_id_and_user_id(user_id, friend_id)
  end

private

  # Creates the inverse {Friendship} if it does not exist
  # @return [Friendship] inverse
  #
  def create_inverse
    inverse or @inverse = Friendship.create( :user_id => friend_id, :friend_id => user_id)
  end

  def destroy_inverse
    inverse.destroy if inverse
    @inverse = nil
  end

end

rails-112911/railsbook/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  def add_comment
    # FIXME: Now You Try, adding comment for this post
  end

  def delete_comment
    # FIXME: Now You Try, deleting comment for this post
  end
end

rails-112911/railsbook/app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic

  has_many :friendships,
    :dependent => :destroy
  has_many :friends,
    :through   => :friendships
  has_many :posts

  # FIXME: Security and validations

  def add_friend(friend)
    raise ArgumentError unless friend
    raise ArgumentError.new("Already friended") if friends.include? friend

    f = Friendship.new :user_id => self.id, :friend_id => friend.id
    return f.save
  end

  def unfriend(friend)
    raise ArgumentError unless friend
    raise ArgumentError.new("Not a friend") unless friends.include? friend

    f = Friendship.find_by_user_id_and_friend_id( self.id, friend.id )
    return f.destroy
  end

end

rails-112911/railsbook/app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

rails-112911/railsbook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user_session, :current_user

  before_filter :current_user_session, :current_user

  private
    def current_user_session
      @current_user_session ||= UserSession.find
    end

    def current_user
      @current_user ||= ( current_user_session && current_user_session.user )
    end

    def require_user
      unless current_user
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_user_session_url
        return false
      end
    end

    def require_no_user
      if current_user
        store_location
        flash[:notice] = "You must be logged out to access this page"
        redirect_to root_url
        return false
      end
    end
    
    def store_location
      session[:return_to] = request.request_uri
    end
    
    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end 
end

rails-112911/railsbook/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if @current_user
      @users = User.all
      @users.delete current_user

      # FIXME: Now You Try, Eager Loading
      friends = @current_user.friends

      @posts = ( [@current_user] | friends).collect(&:posts).flatten.sort_by(&:created_at)
      @posts.reverse!
      render :index
    else
      render :index_logged_out
    end
  end

  def login
  end

end

rails-112911/railsbook/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_user, :only => [:create, :destroy]
  
  def create
    @post = Post.new(params[:post])
    @post.user = current_user
    if @post.save
      flash[:notice] = "Post succesfully created!"
      redirect_back_or_default home_path
    else
      render :action => :new
    end
  end
  
  def destroy
    post = Post.find(params[:id])
    post.destroy if post
    redirect_back_or_default home_path
  end

  def add_comment
    # FIXME: Now You Try, write method for adding comments per post
    # Remember that all of the database/object manipulations should be
    # handled in the model - "fat model, skinny controller"
  end

  def delete_comment
    # FIXME: Now You Try, write method for deleting comments per post
    # Remember that all of the database/object manipulations should be
    # handled in the model - "fat model, skinny controller"
  end
end

rails-112911/railsbook/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy
  
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default home_path
    else
      render :action => :new
    end
  end
  
  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default login_path
  end
end

rails-112911/railsbook/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :except => [:new, :create]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Account registered!"
      redirect_back_or_default root_url
    else
      render :action => :new
    end
  end
  
  def show
    @user = @current_user
  end

  def edit
    @user = @current_user
  end
  
  def update
    @user = @current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to root_url
    else
      render :action => :edit
    end
  end

  def friend
    friend = User.find(params[:friend_id]) rescue nil
    if friend and @current_user.add_friend friend
      flash[:notice] = "You are now friends with #{friend.name}"
    else
    end

    redirect_back_or_default home_path
  end

  def unfriend
    friend = User.find(params[:friend_id]) rescue nil
    if friend and @current_user.unfriend friend
      flash[:notice] = "You are no longer friends with #{friend.name}"
    else
    end

    redirect_back_or_default home_path
  end
end

rails-112911/railsbook/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-112911/railsbook/app/helpers/home_helper.rb
module HomeHelper
end

rails-112911/railsbook/app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

rails-112911/railsbook/app/helpers/users_helper.rb
module UsersHelper
end

rails-112911/railsbook/app/views/home/index.html.erb
<div id="inner-content">
  <div id="people">
    <h2>Friend List</h2>
    <ul class="plain">
      <% for user in @users %>
        <li><%= user.name %>
          <% friend = current_user.friends.include? user %>
          <%= form_tag((friend ? unfriend_path : friend_path), {:class => "inline"}) do %>
            <%= hidden_field_tag :friend_id, user.id %>
            <%= submit_tag (friend ? "Unfriend" : "Friend"), :class => "inline" %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <div id="newsfeed">
  <h2>Newsfeed</h2>
  <div id="status-box" class="clearfix">
    <%= form_tag posts_path do %>
      <%= fields_for :post do |f| %>
        <%= f.text_area :content, :placeholder => "Enter status update here" %>
        <%= f.submit "Post" %>
      <% end %>
    <% end %>
  </div>
  <ul class="plain">
    <% for post in @posts %>
      <li class="newsfeed-item clearfix">
        <div class="newsfeed-item-left">
          <span class="photo"></span>
        </div>
        <div class="newsfeed-item-right">
          <span class="author"><%= post.user.name %></span>
          <span class="content"><%= post.content %></span>
          <span class="time"><%= time_ago_in_words(post.created_at) %> ago</span>
        </div>
        <!-- FIXME: Now You Try: Insert commenting UI -->
      </li>
    <% end %>
  </ul>
    
  </div>
</div>

rails-112911/railsbook/app/views/home/index_logged_out.html.erb
<div id="splash-gradient">
  <div id="inner-content">

    <div class="clearfix">
      <div class="left" style="width: 600px;">
        <h3>Railsbook helps you connect with the Rails app development process.</h3>
        <%= image_tag "splash_map.png" %>
      </div>
      <div class="left" id="register">
        <h3>Sign Up</h3>
        <p>It's better than Facebook.</p>
        <%- form_for User.new, :url => '/register' do |f| -%>
          <%= render :partial => 'users/form', :object => f %>
          <%= f.submit 'Sign Up!' %>
        <%- end -%>
      </div>
    </div>
  </div>
</div>

rails-112911/railsbook/app/views/home/login.html.erb
<h1>Home#login</h1>
<p>Find me in app/views/home/login.html.erb</p>

rails-112911/railsbook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsbook</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="page">
  <%= render :partial => 'shared/navbar' %>
  <%= render 'shared/flash', :flash => flash %>

  <div id="content">
    <%= yield %>
  </div>
</div>

</body>
</html>

rails-112911/railsbook/app/views/shared/_flash.html.erb
<div id="messages">
<% if flash[:notice] %>
  <div id="notice">
    <%= flash[:notice] %>
  </div>
<% end %>
</div>

rails-112911/railsbook/app/views/shared/_login.html.erb
<%# Renders email / password login box.
    @param session [UserSession]
 %>
<div class="login-bar">
  <%= form_for session || UserSession.new, login_path do |f| -%>
    <div class="left" style="margin-right: 0.5em;">
      <%= f.text_field :email, :placeholder => "email address" %>
    </div>
    <div class="left" style="margin-right: 0.5em;">
      <%= f.password_field :password, :placeholder => "password" %>
    </div>

    <div class="right">
      <%= f.submit 'Login', :class => 'login-button' %>
    </div>

  <%- end -%>
</div>

rails-112911/railsbook/app/views/shared/_navbar.html.erb
<div id="navbar" class="clearfix">
  <div id="nav-wrapper">
    <div class="left logo"><%= link_to image_tag("railsbook.png"), root_path %></div>
    <div class="right profile-menu">
      <%- if @current_user -%>
        <%= @current_user.name %>
        <div class="dropdown-menu closed">
          <a class="dropdown-button">&diams;</a>
          <ul class="dropdown-menu-content">
            <li><%= link_to 'Logout', logout_path %></li>
          </ul>
        </div>
      <%- else -%>
        <%= render 'shared/login', :session => @current_user_session %>
      <%- end -%>
    </div>
  </div>
</div>

rails-112911/railsbook/app/views/user_sessions/new.html.erb
<div class="box" style="width: 400px">
  <h2>Login</h2>

  <% form_for @user_session, :url => user_sessions_url do |f| %>
    <%= f.error_messages %>
    <%= f.label :email %><br />
    <%= f.text_field :email %><br />
    <br />
    <%= f.label :password %><br />
    <%= f.password_field :password %><br />
    <br />
    <%= f.check_box :remember_me %><%= f.label :remember_me %><br />
    <br />
    <%= f.submit "Login" %>
  <% end %>
</div>

rails-112911/railsbook/app/views/users/_form.html.erb
<p>
  <%= form.label :email %><br />
  <%= form.text_field :email %><br />
</p>

<p>
  <%= form.label :name %><br />
  <%= form.text_field :name %><br />
</p>

<p>
  <%= form.label :password, form.object.new_record? ? nil : "Change password" %><br />
  <%= form.password_field :password %><br />
</p>

<p>
  <%= form.label :password_confirmation %><br />
  <%= form.password_field :password_confirmation %><br />
</p>

rails-112911/railsbook/app/views/users/new.html.erb
<h1>Register</h1>

<% form_for @user, :url => '/register' do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Register" %>
<% end %>